# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/d3019/OneDrive/Desktop/Vivado Projects/FINAL/ECE414.srcs/sources_1/ip/ip_ram_output_code/ip_ram_output_code.xci
# IP: The module: 'ip_ram_output_code' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/d3019/OneDrive/Desktop/Vivado Projects/FINAL/ECE414.gen/sources_1/ip/ip_ram_output_code/ip_ram_output_code_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_ram_output_code'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/d3019/OneDrive/Desktop/Vivado Projects/FINAL/ECE414.srcs/sources_1/ip/ip_ram_output_code/ip_ram_output_code.xci
# IP: The module: 'ip_ram_output_code' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/d3019/OneDrive/Desktop/Vivado Projects/FINAL/ECE414.gen/sources_1/ip/ip_ram_output_code/ip_ram_output_code_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_ram_output_code'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
