# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/top_level/top_level.xdc

# IP: ip/ip_rom_input_code/ip_rom_input_code.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_rom_input_code || ORIG_REF_NAME==ip_rom_input_code} -quiet] -quiet
